[2024-12-09T10:07:14.701+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-09T10:07:14.849+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:07:06.230150+00:00 [queued]>
[2024-12-09T10:07:14.880+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:07:06.230150+00:00 [queued]>
[2024-12-09T10:07:14.881+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-09T10:07:14.913+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): financial_reports.run_main_report> on 2024-12-09 10:07:06.230150+00:00
[2024-12-09T10:07:14.930+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=614) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-09T10:07:14.931+0000] {standard_task_runner.py:72} INFO - Started process 617 to run task
[2024-12-09T10:07:14.932+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_historycal_financial_reports', 'financial_reports.run_main_report', 'manual__2024-12-09T10:07:06.230150+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/Extract_history_financial_data.py', '--cfg-path', '/tmp/tmprwa8vjrm']
[2024-12-09T10:07:14.936+0000] {standard_task_runner.py:105} INFO - Job 204: Subtask financial_reports.run_main_report
[2024-12-09T10:07:15.125+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_historycal_financial_reports.financial_reports.run_main_report manual__2024-12-09T10:07:06.230150+00:00 [running]> on host 1ce88e57b286
[2024-12-09T10:07:15.597+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='parallel_historycal_financial_reports' AIRFLOW_CTX_TASK_ID='financial_reports.run_main_report' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T10:07:06.230150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-09T10:07:06.230150+00:00'
[2024-12-09T10:07:15.599+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-09T10:08:11.426+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-12-09T10:08:11.428+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-09T10:08:11.431+0000] {process_utils.py:132} INFO - Sending 15 to group 617. PIDs of all processes in the group: [617]
[2024-12-09T10:08:11.431+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 617
[2024-12-09T10:08:11.431+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-09T10:08:11.480+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-09T10:08:11.524+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=617, status='terminated', exitcode=0, started='10:07:14') (617) terminated with exit code 0
