[2024-12-12T14:13:05.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T14:13:05.572+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_historical_price_with_group.process_groups.process_group_1 manual__2024-12-12T14:12:57.981560+00:00 [queued]>
[2024-12-12T14:13:05.614+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_historical_price_with_group.process_groups.process_group_1 manual__2024-12-12T14:12:57.981560+00:00 [queued]>
[2024-12-12T14:13:05.614+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-12T14:13:05.846+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_groups.process_group_1> on 2024-12-12 14:12:57.981560+00:00
[2024-12-12T14:13:05.883+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4052) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-12T14:13:05.891+0000] {standard_task_runner.py:72} INFO - Started process 4065 to run task
[2024-12-12T14:13:05.908+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_historical_price_with_group', 'process_groups.process_group_1', 'manual__2024-12-12T14:12:57.981560+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/Extract_history_price_data.py', '--cfg-path', '/tmp/tmp2g_oaw_8']
[2024-12-12T14:13:05.911+0000] {standard_task_runner.py:105} INFO - Job 354: Subtask process_groups.process_group_1
[2024-12-12T14:13:06.438+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_historical_price_with_group.process_groups.process_group_1 manual__2024-12-12T14:12:57.981560+00:00 [running]> on host f1b774b5d57f
[2024-12-12T14:13:07.130+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflowDWH' AIRFLOW_CTX_DAG_ID='parallel_historical_price_with_group' AIRFLOW_CTX_TASK_ID='process_groups.process_group_1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T14:12:57.981560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T14:12:57.981560+00:00'
[2024-12-12T14:13:07.142+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T14:13:12.334+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:14.489+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:16.193+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:18.312+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:28.486+0000] {job.py:229} INFO - Heartbeat recovered after 11.62 seconds
[2024-12-12T14:13:28.754+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:30.987+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:32.725+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:34.211+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:35.837+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:37.439+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:39.787+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:41.436+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:42.753+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:43.909+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:45.043+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:46.350+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:47.576+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:48.933+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:50.170+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:51.632+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:52.681+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2024-12-12T14:13:52.898+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Extract_history_price_data.py", line 27, in process_group
    result = historical_price(stock_codes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/extract/HistoricalData/Historical_price_stock.py", line 12, in historical_price
    HisPriceDF = stock.quote.history(start='2015-01-01', end='2024-12-7')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vnstock3/common/data/data_explorer.py", line 127, in history
    return self.data_source.history(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vnstock3/explorer/vci/quote.py", line 114, in history
    raise ConnectionError(f"Failed to fetch data: {response.status_code} - {response.reason}")
ConnectionError: Failed to fetch data: 405 - Not Allowed
[2024-12-12T14:13:52.977+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=parallel_historical_price_with_group, task_id=process_groups.process_group_1, run_id=manual__2024-12-12T14:12:57.981560+00:00, execution_date=20241212T141257, start_date=20241212T141305, end_date=20241212T141352
[2024-12-12T14:13:53.050+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T14:13:53.052+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 354 for task process_groups.process_group_1 (Failed to fetch data: 405 - Not Allowed; 4065)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/Extract_history_price_data.py", line 27, in process_group
    result = historical_price(stock_codes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/Tasks/extract/HistoricalData/Historical_price_stock.py", line 12, in historical_price
    HisPriceDF = stock.quote.history(start='2015-01-01', end='2024-12-7')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vnstock3/common/data/data_explorer.py", line 127, in history
    return self.data_source.history(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vnstock3/explorer/vci/quote.py", line 114, in history
    raise ConnectionError(f"Failed to fetch data: {response.status_code} - {response.reason}")
ConnectionError: Failed to fetch data: 405 - Not Allowed
[2024-12-12T14:13:53.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-12T14:13:53.195+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T14:13:53.210+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
